### ISSUE TITLE
Not An Issue

### ISSUE THREAD

**Issue by Crenshaw7860** [mrbentarikau/pagst#1]
I love it, I had one of my friends host it for me since I am unable to host it myself. I would love it if you can get this hosted on digital ocean, or somewhere so anyone can add the bot. I mainly enjoy it because it's a version of YAGPDB the goes on the line of "User Made" in which it's people who suggested things and they have been added to the bot. 

It's like a version of YAGPDB that Updates more often.

I only got to mess around with it a bit till the internet at my friend's was going bad again. So please try and get patreons or something to get this hosted somewhere.
100/10 stars (I totally gave this a star too) and can't wait for more releases

**Comment by mrbentarikau** [comment]
PAGST is already hosted, since Jan this year.
