### ISSUE TITLE
Saving with error

### ISSUE THREAD

**Issue by Crenshaw7860** [mrbentarikau/pagst#2]
when I go to save my code, and there is an error, I get the error message that is appropiete. BUT all the changes I have made go away.
so if I change
`{{ sendMessage nil (print .Channel.Name "Hello") }}`
to
`{{ sendMessage nil (print .Channel.Name "Hello" .Channel.ID }}`
I get the Error "unclosed parentheses yata yata yata"

but my code is what it was before I did any editations.
`{{ sendMessage nil (print .Channel.Name "Hello") }}`

since I have been making, and testing bigger code on pag this is an issue since I don't want to lose progress if there was any legit parts that worked, or if I forget to copy it all loose my progress

**Comment by mrbentarikau** [comment]
writing broken custom commands is not a PAGST issue. as stated, RTFM
