### ISSUE TITLE
Can't add PAGSTDB to new servers

### ISSUE THREAD

**Issue by KangyKSLG** [mrbentarikau/pagst#6]
When I try to get add the bot to a new server I get the below message

![image](https://user-images.githubusercontent.com/42292756/141642863-80caf62d-e4eb-4fd8-8978-e1317cb7c7fd.png)

**Comment by mrbentarikau** [comment]
because of internalization... that's not an issue

**Comment by KangyKSLG** [comment]
So it can no longer be added to servers?

**Comment by mrbentarikau** [comment]
that's true... 
also this repository is not meant to support hosted bot
